# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kmeans.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckmeans.proto\x12\x06kmeans\"\x1c\n\x05Point\x12\x13\n\x0b\x63oordinates\x18\x01 \x03(\x01\"+\n\x08\x43\x65ntroid\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x01\"b\n\rMapperRequest\x12\x12\n\ndata_split\x18\x01 \x01(\t\x12#\n\tcentroids\x18\x02 \x03(\x0b\x32\x10.kmeans.Centroid\x12\x18\n\x10iteration_number\x18\x03 \x01(\x05\"c\n\x0eMapperResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.kmeans.MapperResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"9\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.kmeans.Point\"*\n\x14PartitionDataRequest\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\">\n\rPartitionData\x12-\n\x0fkey_value_pairs\x18\x01 \x03(\x0b\x32\x14.kmeans.KeyValuePair\"i\n\x0eReducerRequest\x12#\n\tcentroids\x18\x01 \x03(\x0b\x32\x10.kmeans.Centroid\x12\x18\n\x10iteration_number\x18\x02 \x01(\x05\x12\x18\n\x10mapper_addresses\x18\x03 \x03(\t\"e\n\x0fReducerResponse\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.kmeans.ReducerResponse.Status\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"\x15\n\x13GetCentroidsRequest\";\n\x14GetCentroidsResponse\x12#\n\tcentroids\x18\x01 \x03(\x0b\x32\x10.kmeans.Centroid2\x99\x01\n\rMapperService\x12=\n\nRunMapTask\x12\x15.kmeans.MapperRequest\x1a\x16.kmeans.MapperResponse\"\x00\x12I\n\x10GetPartitionData\x12\x1c.kmeans.PartitionDataRequest\x1a\x15.kmeans.PartitionData\"\x00\x32\xa1\x01\n\x0eReducerService\x12\x42\n\rRunReduceTask\x12\x16.kmeans.ReducerRequest\x1a\x17.kmeans.ReducerResponse\"\x00\x12K\n\x0cGetCentroids\x12\x1b.kmeans.GetCentroidsRequest\x1a\x1c.kmeans.GetCentroidsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmeans_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=24
  _globals['_POINT']._serialized_end=52
  _globals['_CENTROID']._serialized_start=54
  _globals['_CENTROID']._serialized_end=97
  _globals['_MAPPERREQUEST']._serialized_start=99
  _globals['_MAPPERREQUEST']._serialized_end=197
  _globals['_MAPPERRESPONSE']._serialized_start=199
  _globals['_MAPPERRESPONSE']._serialized_end=298
  _globals['_MAPPERRESPONSE_STATUS']._serialized_start=264
  _globals['_MAPPERRESPONSE_STATUS']._serialized_end=298
  _globals['_KEYVALUEPAIR']._serialized_start=300
  _globals['_KEYVALUEPAIR']._serialized_end=357
  _globals['_PARTITIONDATAREQUEST']._serialized_start=359
  _globals['_PARTITIONDATAREQUEST']._serialized_end=401
  _globals['_PARTITIONDATA']._serialized_start=403
  _globals['_PARTITIONDATA']._serialized_end=465
  _globals['_REDUCERREQUEST']._serialized_start=467
  _globals['_REDUCERREQUEST']._serialized_end=572
  _globals['_REDUCERRESPONSE']._serialized_start=574
  _globals['_REDUCERRESPONSE']._serialized_end=675
  _globals['_REDUCERRESPONSE_STATUS']._serialized_start=264
  _globals['_REDUCERRESPONSE_STATUS']._serialized_end=298
  _globals['_GETCENTROIDSREQUEST']._serialized_start=677
  _globals['_GETCENTROIDSREQUEST']._serialized_end=698
  _globals['_GETCENTROIDSRESPONSE']._serialized_start=700
  _globals['_GETCENTROIDSRESPONSE']._serialized_end=759
  _globals['_MAPPERSERVICE']._serialized_start=762
  _globals['_MAPPERSERVICE']._serialized_end=915
  _globals['_REDUCERSERVICE']._serialized_start=918
  _globals['_REDUCERSERVICE']._serialized_end=1079
# @@protoc_insertion_point(module_scope)
