# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kmeans_pb2 as kmeans__pb2


class MapperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunMapTask = channel.unary_unary(
                '/kmeans.MapperService/RunMapTask',
                request_serializer=kmeans__pb2.MapperRequest.SerializeToString,
                response_deserializer=kmeans__pb2.MapperResponse.FromString,
                )
        self.GetPartitionData = channel.unary_unary(
                '/kmeans.MapperService/GetPartitionData',
                request_serializer=kmeans__pb2.PartitionDataRequest.SerializeToString,
                response_deserializer=kmeans__pb2.PartitionData.FromString,
                )


class MapperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunMapTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartitionData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunMapTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMapTask,
                    request_deserializer=kmeans__pb2.MapperRequest.FromString,
                    response_serializer=kmeans__pb2.MapperResponse.SerializeToString,
            ),
            'GetPartitionData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartitionData,
                    request_deserializer=kmeans__pb2.PartitionDataRequest.FromString,
                    response_serializer=kmeans__pb2.PartitionData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kmeans.MapperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MapperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunMapTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kmeans.MapperService/RunMapTask',
            kmeans__pb2.MapperRequest.SerializeToString,
            kmeans__pb2.MapperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPartitionData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kmeans.MapperService/GetPartitionData',
            kmeans__pb2.PartitionDataRequest.SerializeToString,
            kmeans__pb2.PartitionData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ReducerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunReduceTask = channel.unary_unary(
                '/kmeans.ReducerService/RunReduceTask',
                request_serializer=kmeans__pb2.ReducerRequest.SerializeToString,
                response_deserializer=kmeans__pb2.ReducerResponse.FromString,
                )
        self.GetCentroids = channel.unary_unary(
                '/kmeans.ReducerService/GetCentroids',
                request_serializer=kmeans__pb2.GetCentroidsRequest.SerializeToString,
                response_deserializer=kmeans__pb2.GetCentroidsResponse.FromString,
                )


class ReducerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunReduceTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCentroids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReducerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunReduceTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RunReduceTask,
                    request_deserializer=kmeans__pb2.ReducerRequest.FromString,
                    response_serializer=kmeans__pb2.ReducerResponse.SerializeToString,
            ),
            'GetCentroids': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCentroids,
                    request_deserializer=kmeans__pb2.GetCentroidsRequest.FromString,
                    response_serializer=kmeans__pb2.GetCentroidsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kmeans.ReducerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReducerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunReduceTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kmeans.ReducerService/RunReduceTask',
            kmeans__pb2.ReducerRequest.SerializeToString,
            kmeans__pb2.ReducerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCentroids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kmeans.ReducerService/GetCentroids',
            kmeans__pb2.GetCentroidsRequest.SerializeToString,
            kmeans__pb2.GetCentroidsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
